### ISSUE TITLE
Gather NextGen Automated Testing Notes

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/testing-methods#2]
Notes can be gathered from other repositories and placed in this one. It seemed like the most appropriate place to put things and link to others.

AC:
- [x] Cover the original SFDX repo and success with older Lightning. I got to the part about creating sandboxes https://github.com/CUCentralAdvancement/sf-digitaleng-sandbox/issues/4
- [x] Cover new attempt with Cypress that got derailed because of LWC: https://github.com/CUCentralAdvancement/sf-digitaleng-sandbox/issues/5
- [x] Cover new approach with Codecept: https://github.com/CUCentralAdvancement/sf-digitaleng-sandbox/issues/6
- [x] List next steps and recommendations of consistent step definitions and BDD/Gherkin

**Comment by alexfinnarn** [comment]
I made my notes here: https://github.com/CUCentralAdvancement/testing-methods/blob/main/docs/training-codecept.md
